version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/learning
      - SECRET_KEY=your-secret-key
    volumes:
      - .:/app
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=learning
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
